[functions.stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-sync-subscription]
verify_jwt = true

[functions.stripe-cancel-subscription]
verify_jwt = true
