/*
# Create AI Knowledge Sync tables

## Purpose
Supports the automatic website knowledge discovery and synchronization feature.
When an admin clicks "Update Knowledge", the system scans approved content
sources, generates suggested knowledge entries via OpenAI, and stores them
here for admin review and approval. Approved suggestions become active entries
in the existing ai_knowledge table.

## New Tables

### 1. ai_knowledge_suggestions
Stores pending knowledge entries generated by the sync process, awaiting
administrator approval.
- id (uuid, primary key)
- suggestion_type (text): 'new' | 'updated' | 'conflict' | 'needs_review'
- status (text): 'pending' | 'approved' | 'rejected'
- title (text)
- question (text)
- answer (text)
- category (text)
- keywords (text)
- source_reference (text) — URL or feature name the info was derived from
- discovered_at (timestamptz)
- existing_entry_id (uuid, nullable) — references ai_knowledge.id when type is 'updated' or 'conflict'
- existing_entry_title (text, nullable) — snapshot of existing title for side-by-side comparison
- existing_entry_answer (text, nullable) — snapshot of existing answer for comparison
- sync_run_id (uuid, nullable) — references ai_knowledge_sync_runs.id
- reviewed_at (timestamptz, nullable)
- reviewed_by (uuid, nullable) — auth.users.id of the admin who reviewed
- created_at (timestamptz)
- updated_at (timestamptz)

### 2. ai_knowledge_sync_runs
Tracks each "Update Knowledge" execution for auditing and status display.
- id (uuid, primary key)
- initiated_by (uuid) — auth.users.id of the admin who triggered it
- status (text): 'running' | 'completed' | 'failed'
- pages_scanned (integer)
- suggestions_generated (integer)
- new_count (integer)
- updated_count (integer)
- conflict_count (integer)
- needs_review_count (integer)
- error_message (text, nullable)
- created_at (timestamptz)
- completed_at (timestamptz, nullable)

## Security (RLS)
Both tables are admin-only:
- SELECT: authenticated site admins only
- INSERT: service role only (edge function bypasses RLS)
- UPDATE: authenticated site admins only (for approve/reject)
- DELETE: authenticated site admins only

## Important Notes
1. Pending suggestions are never read by the live AI assistant — only
   approved entries in ai_knowledge are used for live responses.
2. The edge function uses the service role key to insert suggestions,
   bypassing RLS.
3. Normal users cannot access, approve, or reject suggestions.
4. Existing ai_knowledge records are never modified by the sync process
   — only by explicit admin approval.
*/
-- ─────────────────────────────────────────────────────────────────────────────
-- ai_knowledge_suggestions table
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_knowledge_suggestions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  suggestion_type TEXT NOT NULL DEFAULT 'new' CHECK (suggestion_type IN ('new', 'updated', 'conflict', 'needs_review')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  title TEXT NOT NULL,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'General',
  keywords TEXT,
  source_reference TEXT,
  discovered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  existing_entry_id UUID REFERENCES ai_knowledge(id) ON DELETE SET NULL,
  existing_entry_title TEXT,
  existing_entry_answer TEXT,
  sync_run_id UUID,
  reviewed_at TIMESTAMPTZ,
  reviewed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_knowledge_suggestions_status
  ON ai_knowledge_suggestions(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_knowledge_suggestions_type
  ON ai_knowledge_suggestions(suggestion_type);

ALTER TABLE ai_knowledge_suggestions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_select_ai_knowledge_suggestions" ON ai_knowledge_suggestions;
CREATE POLICY "admin_select_ai_knowledge_suggestions" ON ai_knowledge_suggestions
  FOR SELECT TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_site_admin = true)
  );

DROP POLICY IF EXISTS "admin_update_ai_knowledge_suggestions" ON ai_knowledge_suggestions;
CREATE POLICY "admin_update_ai_knowledge_suggestions" ON ai_knowledge_suggestions
  FOR UPDATE TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_site_admin = true)
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_site_admin = true)
  );

DROP POLICY IF EXISTS "admin_delete_ai_knowledge_suggestions" ON ai_knowledge_suggestions;
CREATE POLICY "admin_delete_ai_knowledge_suggestions" ON ai_knowledge_suggestions
  FOR DELETE TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_site_admin = true)
  );

-- No INSERT policy for client roles — only the service role (edge function) inserts.

-- ─────────────────────────────────────────────────────────────────────────────
-- ai_knowledge_sync_runs table
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_knowledge_sync_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  initiated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'completed', 'failed')),
  pages_scanned INTEGER NOT NULL DEFAULT 0,
  suggestions_generated INTEGER NOT NULL DEFAULT 0,
  new_count INTEGER NOT NULL DEFAULT 0,
  updated_count INTEGER NOT NULL DEFAULT 0,
  conflict_count INTEGER NOT NULL DEFAULT 0,
  needs_review_count INTEGER NOT NULL DEFAULT 0,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_ai_knowledge_sync_runs_created_at
  ON ai_knowledge_sync_runs(created_at DESC);

ALTER TABLE ai_knowledge_sync_runs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_select_ai_knowledge_sync_runs" ON ai_knowledge_sync_runs;
CREATE POLICY "admin_select_ai_knowledge_sync_runs" ON ai_knowledge_sync_runs
  FOR SELECT TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_site_admin = true)
  );

DROP POLICY IF EXISTS "admin_delete_ai_knowledge_sync_runs" ON ai_knowledge_sync_runs;
CREATE POLICY "admin_delete_ai_knowledge_sync_runs" ON ai_knowledge_sync_runs
  FOR DELETE TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_site_admin = true)
  );
